#!/usr/bin/env python
import sys
import json
import datetime
import re

filename = sys.argv[1]

contents = ""
with open(filename) as f:
    contents = f.read()

contents = json.loads(contents)
sub_totals = {}
total = datetime.timedelta()

for item in contents:
    if "elapsed" not in item:
        continue

    key = "OTHER"

    if ":" in item["name"]:
        key = re.search(".*?(?=:)", item["name"]).group(0)

    elapsed = item["elapsed"]
    d = datetime.datetime.strptime(elapsed, "%H:%M:%S.%f")
    delta = datetime.timedelta(hours=d.hour, minutes=d.minute, seconds=d.second, microseconds=d.microsecond)
    if key not in sub_totals:
        sub_totals[key] = delta
    else:
        sub_totals[key] += delta

    total += delta

for total_type, delta in sub_totals.iteritems():
    print "{0}: {1}".format(total_type, delta)


print "{0}: {1}".format("Total", total)
