#!/usr/bin/env python

import datetime
import dateutil.parser
import os
import json
date = datetime.datetime.now()

today = date.strftime("%Y-%m-%d")

if not os.path.isfile(today):
    # like touch
    open(today, "w").close()


class RecordReader(object):
    def __init__(self, file_name):
        self.file_name = file_name
        self.record_list = []

    def read(self):
        with open(self.file_name, "r") as f:
            content = f.read().strip()

            if content:
                self.record_list = json.loads(content)

    def last_record(self):
        last = None
        if len(self.record_list):
            last = self.record_list[-1]

        return last

    def add_record(self, record):
        self.record_list.append(record)

    def write(self):
        content = json.dumps(self.record_list)
        with open(self.file_name, "w") as f:
            f.write(content)

reader = RecordReader(today)
reader.read()

while True:
    name = raw_input("> Name : ")
    last_record = reader.last_record()
    now = datetime.datetime.now()
    if last_record:
        last_record["end"] = now.isoformat()
        start = dateutil.parser.parse(last_record["start"])
        delta = now - start
        delta_str = str(delta)
        last_record["elapsed"] = delta_str
        print "Elapsed Time : %s" % delta_str

    record = {
        "name": name,
        "start": now.isoformat()
    }

    reader.add_record(record)
    reader.write()
